### ISSUE TITLE
Nice To Have: Status Page/Notifications.

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/broadway-api#18]
It'd be nice to have a quick and easy status page (bonus points for automatic per-job slack integration) to see when the ag is stalling or fails.

**Comment by nmagerko** [comment]
Let's not bundle front-end things into the API. 

I've always liked the idea of an endpoint for grading run progress and maybe some configurable callback for when jobs or complete, etc, but I think it might be a mistake to have anything but the API as part of this service.

**Comment by bhuvy2** [comment]
If nothing web-dev-y would a status.txt endpoint be fine?

**Comment by ayushr2** [comment]
I already have an endpoint (which I have not implemented yet) for getting job statuses.
[endpoint definition](https://github.com/illinois-cs241/broadway-api/blob/master/src/api.py#L90)

**Comment by nmagerko** [comment]
I don't think there's really any reason for the API to be serving/sending text files when the normal JSON payload would make sense. Let's plan on having that endpoint provide the status for jobs.

**Comment by bhuvy2** [comment]
@ayushr2 Was this resolved with the status api?

**Comment by ayushr2** [comment]
> @ayushr2 Was this resolved with the status API?

@bhuvy2 There are few changes we need to make. Currently, we only expose an endpoint to get the grading run status. What we want is the grading job status. We need to figure out a clean way of exposing the job ids and an endpoint to give the job status.

**Comment by ayushr2** [comment]
I think this was largely implemented in #46 which enables courses to get the status of a run using the grading run id and also the status of all the stages with their job ids.
