### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ayushr2** [illinois-cs241/broadway-api#27]
- README: general folder level info with the top level being a tldr; of the entire project
- Docstrings document functions, classes, and what the APIs look like for api function
- Wiki includes how to contribute, more in depth getting started, release notes. Endpoints description and how to use them.

**Comment by nmagerko** [comment]
Let's leave docstrings for last and focus on making the README really just the what-you-need-to-get-started stuff, and the Wiki the API documentation/discussion on specific topics. 

Docstrings will be changing fairly frequently as the other issues are addressed.

**Comment by nmagerko** [comment]
Bump on this, but for the general documentation. The README needs a lot of help.

**Comment by ayushr2** [comment]
I think the Wiki has been updated to accommodate this.
