### ISSUE TITLE
Refactor Database Interaction

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/broadway-api#29]
Currently the database interactions are "baked into" the api -- meaning that while the api is processing it makes database requests.

Just as a bow to code cleanliness, we should keep these interactions entirely in another module -- especially if we see a need to switch to another database provider in the future (mongo is generally more performant than other databases in a vacuum, but if the deployer already has a campus cluster of ferpa compliant MySQL instances, I doubt that they'll spend engineering effort conjuring up and maintaining a new mongo cluster).

**Comment by nmagerko** [comment]
I'm planning on doing a refactor of the module to increase maintainability/clarity of some components, so when I start that I can make a DAO or something.
