### ISSUE TITLE
We need HTTPS

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/broadway-api#34]
This is critical to support truly authenticated courses. Right now all of the infrastructure is on a separate, federated sub network, so no one should be able to listen in on traffic.

Acceptance criteria: Make sure that **no** requests are sent with HTTP and enable HTTPS

https://stackoverflow.com/questions/18307131/how-to-create-https-tornado-server

**Comment by ayushr2** [comment]
Resolved in #36
