### ISSUE TITLE
Add --cap-add to statge config

### ISSUE THREAD

**Issue by rod-lin** [illinois-cs241/broadway-api#38]
Hi, I recently added unshare support in https://github.com/illinois-cs241/docker-tools/pull/8 to containerize each tester, but that would require docker to be run with `--cap-add SYS_ADMIN --cap-add NET_ADMIN -e USE_UNSHARE=true`.

Is it possible to allow stage config to change the capability of the user inside docker? e.g. add an entry in stage config like this `capability: [ SYS_ADMIN, ... ]`

**Comment by ayushr2** [comment]
Yes, this is doable. We can add a new optional field in the grading stage definition. Appropriate changes will have to be made to the docker runner to account for this.
