### ISSUE TITLE
Extend API to allow for Packaged Containers

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/broadway-api#60]
There are some classes that will not open source their autograders and don't want to.
If we don't have a private dockerhub set up for the university, could we potentially take the coursera approach and install a `tar.gz` docker container instead.

Instead of changing the required fields, could we also have the image be an http/s link that is `wget` from.

'image': 'http://path.to/docker/container.tar.gz',

and each of the graders would tar.gz. Of course there is a problem if that URL is leaked, but that would have to be a Course Instructor error, not a broadway error.

Graders would wget and get the container that way.

Thoughts?

**Comment by ayushr2** [comment]
I like the idea. Could we shift this to [ChainLink](https://github.com/illinois-cs241/chainlink) since this does not require any change in Broadway API? ChainLink has to decide if the image is an https link or docker hub image name.

**Comment by bhuvy2** [comment]
Do we have any validators here or is it passed to broadway api? Plus we will need docs changes.

**Comment by ayushr2** [comment]
No validators here. Broadway API does not interact at all with Docker. It directly passes this to the worker nodes.

**Comment by bhuvy2** [comment]
Will create sister issue in grader.

**Comment by ayushr2** [comment]
Will close this as the sister issue was closed. illinois-cs241/chainlink#23.
