### ISSUE TITLE
Improve flags and configuration

### ISSUE THREAD

**Issue by rod-lin** [illinois-cs241/broadway-api#67]
Right now the fixed `config.py` doesn't work very well with docker and is also hard to generate with templates since it's not a standard data format.

We could potentially switch to yaml for configuration and add a set of environment variables for overriding flags.

**Comment by ayushr2** [comment]
Are we having a use case where an external service is trying to set up `config.py`? Till now it was only intended to be set by the person running the API.

Could we use JSON instead of yaml as that is the more frequently used data format in this project?

**Comment by rod-lin** [comment]
yeah I was trying to set it up with salt. Also dockerizing grader and API might make it easier to deploy?
(JSON is also perfect)

**Comment by ayushr2** [comment]
I agree, dockerizing them seems like a good idea.

**Comment by zhengyao-lin** [comment]
Already merged into the new repo https://github.com/illinois-cs241/broadway
